payments_risk:
  target: "{{ env_var('DBT_TARGET', 'local') }}"
  outputs:
    local:
      type: duckdb
      path: "{{ env_var('DUCKDB_PATH', '../data/local.duckdb') }}"
      schema: analytics
    snowflake:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE', 'SYSADMIN') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE', 'RISK_WH') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE', 'PAYMENTS_RISK') }}"
      schema: analytics
      threads: 4
